---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/login":
    post:
      summary: Autentica al usuario
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: Usuario autenticado
        '401':
          description: Credenciales inválidas
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/register":
    post:
      summary: Registra un nuevo usuario
      tags:
      - Auth
      parameters: []
      responses:
        '201':
          description: Usuario registrado
        '422':
          description: Error en el registro
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - name
              - email
              - password
              - password_confirmation
  "/bitcoin_price":
    get:
      summary: Obtiene el precio de Bitcoin en USD
      tags:
      - BitcoinPrice
      responses:
        '200':
          description: Precio de Bitcoin en USD encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  btc_price_in_usd:
                    type: number
        '503':
          description: Servicio no disponible
  "/users/{user_id}/transactions":
    get:
      summary: Lista de transacciones del usuario
      tags:
      - Transactions
      parameters:
      - name: user_id
        in: path
        description: ID del usuario
        required: true
        schema:
          type: integer
      security:
      - Bearer: []
      responses:
        '200':
          description: Lista de transacciones encontrada
        '404':
          description: Usuario no encontrado
  "/transactions":
    post:
      summary: Crea una nueva transacción
      tags:
      - Transactions
      parameters: []
      security:
      - Bearer: []
      responses:
        '201':
          description: Transacción creada
        '422':
          description: Error en la creación de la transacción
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currency_sent:
                  type: string
                currency_received:
                  type: string
                amount_sent:
                  type: number
              required:
              - currency_sent
              - currency_received
              - amount_sent
  "/transactions/{id}":
    get:
      summary: Obtiene una transacción específica
      tags:
      - Transactions
      parameters:
      - name: id
        in: path
        description: ID de la transacción
        required: true
        schema:
          type: integer
      security:
      - Bearer: []
      responses:
        '200':
          description: Transacción encontrada
        '404':
          description: Transacción no encontrada
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
      description: Token de autenticación usando el esquema Bearer (Bearer {token}),
        se obtiene al realizar login
