default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'postgres' } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT") { 'crypto_transact_dev_db' } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST") { 'crypto_transact_staging_db' } %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PRODUCTION") { 'crypto_transact_prod_db' } %>
  username: <%= ENV.fetch("DB_USERNAME_PRODUCTION") { 'production_user' } %>
  password: <%= ENV.fetch("DB_PASSWORD_PRODUCTION") { 'production_password' } %>

